services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-spacr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-spacr}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "8081:5432"
    networks:
      - spacr_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-spacr@spacr.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-spacr}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - spacr_network
    restart: unless-stopped

networks:
  spacr_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
