import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Constellation from '#models/constellation'

export default class extends BaseSeeder {
  async run() {
    const constellations = [
      { code: 'AND', fullName: 'Andromeda', description: 'The Chained Maiden' },
      { code: 'ANT', fullName: 'Antlia', description: 'The Air Pump' },
      { code: 'APS', fullName: 'Apus', description: 'The Bird of Paradise' },
      { code: 'AQR', fullName: 'Aquarius', description: 'The Water Bearer' },
      { code: 'AQL', fullName: 'Aquila', description: 'The Eagle' },
      { code: 'ARA', fullName: 'Ara', description: 'The Altar' },
      { code: 'ARI', fullName: 'Aries', description: 'The Ram' },
      { code: 'AUR', fullName: 'Auriga', description: 'The Charioteer' },
      { code: 'BOO', fullName: 'Boötes', description: 'The Herdsman' },
      { code: 'CAE', fullName: 'Caelum', description: 'The Chisel' },
      { code: 'CAM', fullName: 'Camelopardalis', description: 'The Giraffe' },
      { code: 'CNC', fullName: 'Cancer', description: 'The Crab' },
      { code: 'CVN', fullName: 'Canes Venatici', description: 'The Hunting Dogs' },
      { code: 'CMA', fullName: 'Canis Major', description: 'The Great Dog' },
      { code: 'CMI', fullName: 'Canis Minor', description: 'The Little Dog' },
      { code: 'CAP', fullName: 'Capricornus', description: 'The Sea Goat' },
      { code: 'CAR', fullName: 'Carina', description: 'The Keel' },
      { code: 'CAS', fullName: 'Cassiopeia', description: 'The Queen' },
      { code: 'CEN', fullName: 'Centaurus', description: 'The Centaur' },
      { code: 'CEP', fullName: 'Cepheus', description: 'The King' },
      { code: 'CET', fullName: 'Cetus', description: 'The Whale' },
      { code: 'CHA', fullName: 'Chamaeleon', description: 'The Chameleon' },
      { code: 'CIR', fullName: 'Circinus', description: 'The Compass' },
      { code: 'COL', fullName: 'Columba', description: 'The Dove' },
      { code: 'COM', fullName: 'Coma Berenices', description: "Berenice's Hair" },
      { code: 'CRA', fullName: 'Corona Australis', description: 'The Southern Crown' },
      { code: 'CRB', fullName: 'Corona Borealis', description: 'The Northern Crown' },
      { code: 'CRV', fullName: 'Corvus', description: 'The Crow' },
      { code: 'CRT', fullName: 'Crater', description: 'The Cup' },
      { code: 'CRU', fullName: 'Crux', description: 'The Southern Cross' },
      { code: 'CYG', fullName: 'Cygnus', description: 'The Swan' },
      { code: 'DEL', fullName: 'Delphinus', description: 'The Dolphin' },
      { code: 'DOR', fullName: 'Dorado', description: 'The Goldfish' },
      { code: 'DRA', fullName: 'Draco', description: 'The Dragon' },
      { code: 'EQU', fullName: 'Equuleus', description: 'The Little Horse' },
      { code: 'ERI', fullName: 'Eridanus', description: 'The River' },
      { code: 'FOR', fullName: 'Fornax', description: 'The Furnace' },
      { code: 'GEM', fullName: 'Gemini', description: 'The Twins' },
      { code: 'GRU', fullName: 'Grus', description: 'The Crane' },
      { code: 'HER', fullName: 'Hercules', description: 'The Hero' },
      { code: 'HOR', fullName: 'Horologium', description: 'The Clock' },
      { code: 'HYA', fullName: 'Hydra', description: 'The Water Snake' },
      { code: 'HYI', fullName: 'Hydrus', description: 'The Lesser Water Snake' },
      { code: 'IND', fullName: 'Indus', description: 'The Indian' },
      { code: 'LAC', fullName: 'Lacerta', description: 'The Lizard' },
      { code: 'LEO', fullName: 'Leo', description: 'The Lion' },
      { code: 'LMI', fullName: 'Leo Minor', description: 'The Little Lion' },
      { code: 'LEP', fullName: 'Lepus', description: 'The Hare' },
      { code: 'LIB', fullName: 'Libra', description: 'The Scales' },
      { code: 'LUP', fullName: 'Lupus', description: 'The Wolf' },
      { code: 'LYN', fullName: 'Lynx', description: 'The Lynx' },
      { code: 'LYR', fullName: 'Lyra', description: 'The Lyre' },
      { code: 'MEN', fullName: 'Mensa', description: 'The Table Mountain' },
      { code: 'MIC', fullName: 'Microscopium', description: 'The Microscope' },
      { code: 'MON', fullName: 'Monoceros', description: 'The Unicorn' },
      { code: 'MUS', fullName: 'Musca', description: 'The Fly' },
      { code: 'NOR', fullName: 'Norma', description: "The Carpenter's Square" },
      { code: 'OCT', fullName: 'Octans', description: 'The Octant' },
      { code: 'OPH', fullName: 'Ophiuchus', description: 'The Serpent Bearer' },
      { code: 'ORI', fullName: 'Orion', description: 'The Hunter' },
      { code: 'PAV', fullName: 'Pavo', description: 'The Peacock' },
      { code: 'PEG', fullName: 'Pegasus', description: 'The Winged Horse' },
      { code: 'PER', fullName: 'Perseus', description: 'The Hero' },
      { code: 'PHE', fullName: 'Phoenix', description: 'The Phoenix' },
      { code: 'PIC', fullName: 'Pictor', description: "The Painter's Easel" },
      { code: 'PSC', fullName: 'Pisces', description: 'The Fishes' },
      { code: 'PSA', fullName: 'Piscis Austrinus', description: 'The Southern Fish' },
      { code: 'PUP', fullName: 'Puppis', description: 'The Stern' },
      { code: 'PYX', fullName: 'Pyxis', description: 'The Compass' },
      { code: 'RET', fullName: 'Reticulum', description: 'The Reticle' },
      { code: 'SGE', fullName: 'Sagitta', description: 'The Arrow' },
      { code: 'SGR', fullName: 'Sagittarius', description: 'The Archer' },
      { code: 'SCO', fullName: 'Scorpius', description: 'The Scorpion' },
      { code: 'SCL', fullName: 'Sculptor', description: 'The Sculptor' },
      { code: 'SCT', fullName: 'Scutum', description: 'The Shield' },
      { code: 'SER', fullName: 'Serpens', description: 'The Serpent' },
      { code: 'SEX', fullName: 'Sextans', description: 'The Sextant' },
      { code: 'TAU', fullName: 'Taurus', description: 'The Bull' },
      { code: 'TEL', fullName: 'Telescopium', description: 'The Telescope' },
      { code: 'TRI', fullName: 'Triangulum', description: 'The Triangle' },
      { code: 'TRA', fullName: 'Triangulum Australe', description: 'The Southern Triangle' },
      { code: 'TUC', fullName: 'Tucana', description: 'The Toucan' },
      { code: 'UMA', fullName: 'Ursa Major', description: 'The Great Bear' },
      { code: 'UMI', fullName: 'Ursa Minor', description: 'The Little Bear' },
      { code: 'VEL', fullName: 'Vela', description: 'The Sails' },
      { code: 'VIR', fullName: 'Virgo', description: 'The Virgin' },
      { code: 'VOL', fullName: 'Volans', description: 'The Flying Fish' },
      { code: 'VUL', fullName: 'Vulpecula', description: 'The Fox' },
    ]

    for (const constellation of constellations) {
      await Constellation.create(constellation)
    }
  }
}
